IdentitySQLDemo/Controllers/SupplyController.cs
using IdentitySQLDemo.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using AspNet.Identity.MySQL;
using IdentitySQLDemo.DB_layer;

namespace IdentitySQLDemo.Controllers
{
    public class SupplyController : Controller
    {
        //
        // GET: /Supply/
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult GRN_Inset()
        {
            return View();
        }
        // insert to GRN

        [Authorize]
        [HttpPost]
        public ActionResult GRN_Inset(GRN variable1)
        {
            string query2 = "Insert into GRN (GRN_NO,Supplier_id,Descriptions,Date,Ordered_Quantity,Delivered_Quantity,Total_Value,Discount) values ('" + variable1.GRN_NO + "'," + variable1.Supplier_id + ",'" + variable1.Descriptions + "', '" + variable1.Date + "', " + variable1.Ordered_Quantity + " ," + variable1.Delivered_Quantity + "," + variable1.Total_Value + "," + variable1.Discount + ")";
           new ExecuteSqlCommand(query2).ExecuteInsertCommad();

            return View();
        }

        //insert multiple grn
        [Authorize]
        public ActionResult GRN_Insetmulti()
        {
            List<GRN> grn = new List<GRN> { new GRN { GRN_NO = "", Supplier_id = 0, Descriptions = "", Date = "", Ordered_Quantity = 0, Delivered_Quantity = 0, Total_Value = 0, Discount = 0 } };
            return View(grn);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GRN_Insetmulti(List<GRN> grn)
        {
            if (ModelState.IsValid)
            {

                foreach (var grns in grn)
                {
                    string query2 = "Insert into GRN(GRN_NO,Supplier_id,Descriptions,Date,Ordered_Quantity,Delivered_Quantity,Total_Value,Discount values (" + grns.GRN_NO + "," + grns.Supplier_id + ",'" + grns.Descriptions + "', '" + grns.Date + "', " + grns.Ordered_Quantity + "," + grns.Delivered_Quantity + " ," + grns.Total_Value + "," + grns.Discount + " )";
                    new ExecuteSqlCommand(query2).ExecuteInsertCommad();

                }
            }
            return View(grn);

        }


        //view GRN
        [Authorize]
        public ActionResult GRN_view()
        {

            string name2 = "SELECT GRN_NO,Supplier_id,Descriptions,Date,Ordered_Quantity,Delivered_Quantity,Total_Value,Discount FROM GRN  ";
            List<GRN> LIST1 = new List<GRN>();
            LIST1 = new BusinessLayer(name2).GetGrn();

            return View(LIST1);

        }

        [Authorize]
        [HttpGet]
        public ActionResult GRN_Edit(int grno)
        {

            SqlConnection Sales = new ExecuteSqlCommand().getConnection();

            string name2 = "SELECT GRN_NO,Supplier_id,Descriptions,Date,Ordered_Quantity,Delivered_Quantity,Total_Value,Discount FROM GRN where GRN_NO=" + grno;
            List<GRN> LIST1 = new List<GRN>();
            LIST1 = new BusinessLayer(name2).GetGrn();

            return View(LIST1.ElementAt(0));

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GRN_Edit(GRN variable2)
        {
            string query4 = "Update GRN set GRN_NO=" + variable2.GRN_NO + ",Supplier_id=" + variable2.Supplier_id + ",Descriptions='" + variable2.Descriptions + "', Date='" + variable2.Date + "', Ordered_Quantity =" + variable2.Ordered_Quantity + ",Delivered_Quantity=" + variable2.Delivered_Quantity + " ,Total_Value=" + variable2.Total_Value + ",Discount=" + variable2.Discount + "  ";
            new ExecuteSqlCommand(query4).ExecuteInsertCommad();
            ViewBag.Message = "Data succesfully saved";

            return RedirectToAction("GRN_view");
        }


        //Delete sales order 
        [Authorize]
        [HttpGet]
        public ActionResult GRN_Delete(int grno)
        {

            SqlConnection Sales2 = new ExecuteSqlCommand().getConnection();

            string name2 = "SELECT GRN_NO,Supplier_id,Descriptions,Date,Ordered_Quantity,Delivered_Quantity,Total_Value,Discount FROM GRN WHERE GRN_NO=" + grno;
            List<GRN> LIST1 = new List<GRN>();

            SqlCommand Sales3 = new SqlCommand(name2, Sales2);
            Sales2.Open();
            var read = Sales3.ExecuteReader();
            GRN grn = new GRN();
            while (read.Read())
            {



                grn.GRN_NO = read["GRN_NO"].ToString();
                grn.Supplier_id = Convert.ToInt32(read["Supplier_id"]);
                grn.Descriptions = read["Descriptions"].ToString();
                grn.Date = read["Date"].ToString();
                grn.Ordered_Quantity = Convert.ToInt32(read["Ordered_Quantity"]);
                grn.Delivered_Quantity = Convert.ToInt32(read["Delivered_Quantity"]);
                grn.Total_Value = Convert.ToInt32(read["Total_Value"]);
                grn.Discount = Convert.ToInt32(read["Discount"]);
                //grn.Net_Value = Convert.ToInt32(read["Net_Value"]);






            }
            Sales2.Close();

            return View(grn);

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GRN_Delete(GRN variable3)
        {

            SqlConnection Sales6 = new ExecuteSqlCommand().getConnection();
            string deleteQuery = "DELETE  FROM GRN WHERE GRN_NO = " + variable3.GRN_NO;
            SqlCommand name5 = new SqlCommand(deleteQuery, Sales6);
            Sales6.Open();
            name5.ExecuteNonQuery();
            Sales6.Close();


            return RedirectToAction("GRN_view");

        }

        //SALES RETURN METHODS
        [Authorize]
        [HttpGet]
        public ActionResult Sales_Return_Order_Inset()
        {
            return View();
        }
        // insert to Sales return order
        [Authorize]
        [HttpPost]
        public ActionResult Sales_Return_Order_Inset(Sales_Return_Order variable2)
        {

            SqlConnection Sales1 = new ExecuteSqlCommand().getConnection();
            string query1 = "Insert into Sales_Return_Order(SalesRe_No,Invoice_No,Supplier_id,Descriptions,Date,Quntity ,Unit_Price ) values (" + variable2.SalesRe_No + "," + variable2.Invoice_No + "," + variable2.Supplier_id + ",'" + variable2.Descriptions + "', '" + variable2.Date + "', " + variable2.Quntity + " ," + variable2.Unit_Price + ")";
            SqlCommand name5 = new SqlCommand(query1, Sales1);
            Sales1.Open();
            name5.ExecuteNonQuery();
            Sales1.Close();


            return RedirectToAction("Sales_Return_Order_view");

        }


        //insert multiple data into the sales return order

        [Authorize]
        public ActionResult Sales_Return_Order_Insetmulti()
        {
            List<Sales_Return_Order> sro = new List<Sales_Return_Order> { new Sales_Return_Order { SalesRe_No = 0, Invoice_No = 0, Supplier_id = 0, Descriptions = "", Date = "", Quntity = 0, Unit_Price = 0 } };
            return View(sro);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sales_Return_Order_Insetmulti(List<Sales_Return_Order> sro)
        {
            if (ModelState.IsValid)
            {

                SqlConnection Sales3 = new ExecuteSqlCommand().getConnection();

                Sales3.Open();
                foreach (var sros in sro)
                {
                    string query2 = "Insert into Sales_Return_Order (SalesRe_No,Invoice_No,Supplier_id,Descriptions,Date,Quntity,Unit_Price) values (" + sros.SalesRe_No + "," + sros.Invoice_No + "," + sros.Supplier_id + ",'" + sros.Descriptions + "', '" + sros.Date + "', " + sros.Quntity + "," + sros.Unit_Price + "  )";
                    SqlCommand name4 = new SqlCommand(query2, Sales3);

                    name4.ExecuteNonQuery();

                }
                Sales3.Close();

            }
            return View(sro);

        }

        //view sales return order
        [Authorize]
        public ActionResult Sales_Return_Order_view()
        {


            SqlConnection Sales2 = new ExecuteSqlCommand().getConnection();

            string name6 = "SELECT SalesRe_No,Invoice_No,Supplier_id,Descriptions,Date,Quntity,Unit_Price FROM   Sales_Return_Order  ";
            List<Sales_Return_Order> LIST1 = new List<Sales_Return_Order>();

            SqlCommand Sales3 = new SqlCommand(name6, Sales2);
            Sales2.Open();
            var read = Sales3.ExecuteReader();
            while (read.Read())
            {

                Sales_Return_Order SRO = new Sales_Return_Order();

                SRO.SalesRe_No = Convert.ToInt32(read["SalesRe_No"]);
                SRO.Invoice_No = Convert.ToInt32(read["Invoice_No"]);
                SRO.Supplier_id = Convert.ToInt32(read["Supplier_id"]);
                SRO.Descriptions = read["Descriptions"].ToString();
                SRO.Date = read["Date"].ToString();
                SRO.Quntity = Convert.ToInt32(read["Quntity"]);
                SRO.Unit_Price = Convert.ToInt32(read["Unit_Price"]);
                //SO.Total_price = Convert.ToInt32(read["Total_price"]);
                LIST1.Add(SRO);




            }
            Sales2.Close();

            return View(LIST1);


        }



        //Edit sales return order

        [Authorize]
        [HttpGet]
        public ActionResult Sales_Return_Order_Edit(int srn)
        {


            SqlConnection Sales4 = new ExecuteSqlCommand().getConnection();

            string name3 = "SELECT  SalesRe_No, Invoice_No ,Supplier_id , Descriptions,Date,Quntity,Unit_Price FROM Sales_Return_Order   WHERE SalesRe_No =" + srn;
            List<Sales_Return_Order> LIST2 = new List<Sales_Return_Order>();

IdentitySQLDemo/Views/Supply/GRN_Delete.cshtml
@model IdentitySQLDemo.Models.GRN

@{
    ViewBag.Title = "GRN_Delete";
    
}

<h2>GRN_Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GRN</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.GRN_NO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GRN_NO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descriptions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descriptions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ordered_Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ordered_Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Delivered_Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivered_Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Net_Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Net_Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Net_Values)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Net_Values)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "GRN_view", "Supply")
        </div>
    }
</div>

IdentitySQLDemo/Views/Supply/GRN_Edit.cshtml
@model IdentitySQLDemo.Models.GRN

@{
    ViewBag.Title = "GRN_Edit";
    
}

<h2>GRN_Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GRN</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.GRN_NO, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GRN_NO)
                @Html.ValidationMessageFor(model => model.GRN_NO)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplier_id)
                @Html.ValidationMessageFor(model => model.Supplier_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descriptions, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descriptions)
                @Html.ValidationMessageFor(model => model.Descriptions)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ordered_Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ordered_Quantity)
                @Html.ValidationMessageFor(model => model.Ordered_Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Delivered_Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Delivered_Quantity)
                @Html.ValidationMessageFor(model => model.Delivered_Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_Value, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_Value)
                @Html.ValidationMessageFor(model => model.Total_Value)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discount)
                @Html.ValidationMessageFor(model => model.Discount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Net_Value, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Net_Value)
                @Html.ValidationMessageFor(model => model.Net_Value)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GRN_view", "Supply")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdentitySQLDemo/Views/Supply/GRN_view.cshtml
@model IEnumerable<IdentitySQLDemo.Models.GRN>

@{
    ViewBag.Title = "GRN";
    
    }
<h2>Goods Received Note</h2>

<p>
    @Html.ActionLink("Create New", "GRN_Inset", "Supply")
</p>
@*<p>
    Supplier_id : @Html.DropDownList("SupplierID", "All")
    GRN_NO: @Html.TextBox("strSearch")
    <input type="submit" value="Search" />
</p>*@
        
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GRN_NO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descriptions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ordered_Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Delivered_Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discount)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Net_Value)
        </th*@
        <th>
            @Html.DisplayNameFor(model => model.Net_Values)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GRN_NO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descriptions)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ordered_Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Delivered_Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total_Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discount)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Net_Value)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Net_Values)
        </td>
        <td>
            @Html.ActionLink("Edit", "GRN_Edit", "Supply", new { grno = item.GRN_NO }, null) |
            @*@Html.ActionLink("Details", "Details", new {  grno=item.GRN_NO }) |*@
            @Html.ActionLink("Delete", "GRN_Delete", "Supply", new { grno = item.GRN_NO }, null)
            <button type="button" id="modal-opener" onclick="openModel()">Open Dialog</button>

        </td>
    </tr>
}

</table>

<div id="dialog-modal" title="Modal dialog">
    <input type="text" class="text-success" id="receiver" />
    <button type="button" class="btn-danger" id="modalrunner" onclick="closeModal()">Athorize</button>

    @Html.DropDownList("Type", new List<SelectListItem>{
                new SelectListItem{ Text = "Urgant", Value = "urgent" },
                new SelectListItem{ Text = "Normal", Value = "normal" },
            })
</div>
<script type="text/javascript">
    function closeModal() {
        $('#modalrunner').click(function () {


            $('#dialog-modal').dialog("close");

        });
    }

    
</script>

IdentitySQLDemo/Views/Supply/Sales_Order_Inset.cshtml
@model IdentitySQLDemo.Models.Sales_Order

@{
    ViewBag.Title = "Insert New Sales Orders";
    
}<div style="float:left; padding-left:200px;">
    
        <h2>Insert New Sales Orders</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4> Enter Sales Orders</h4>
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.Invoice_No, new { @class = "control-label col-md-5" })
                    <div class="col-md-19">
                        @Html.EditorFor(model => model.Invoice_No)
                        @Html.ValidationMessageFor(model => model.Invoice_No)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Supplier_id, new { @class = "control-label col-md-5" })
                    <div class="col-md-19">
                        @Html.EditorFor(model => model.Supplier_id)
                        @Html.ValidationMessageFor(model => model.Supplier_id)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descriptions, new { @class = "control-label col-md-5" })
                    <div class="col-md-19">
                        @Html.EditorFor(model => model.Descriptions)
                        @Html.ValidationMessageFor(model => model.Descriptions)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-5" })
                    <div class="col-md-19">
                        @Html.EditorFor(model => model.Date)
                        @Html.ValidationMessageFor(model => model.Date)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quntity, new { @class = "control-label col-md-5" })
                    <div class="col-md-19">
                        @Html.EditorFor(model => model.Quntity)
                        @Html.ValidationMessageFor(model => model.Quntity)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Unit_Price, new { @class = "control-label col-md-5" })
                    <div class="col-md-19">
                        @Html.EditorFor(model => model.Unit_Price)
                        @Html.ValidationMessageFor(model => model.Unit_Price)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" id="authanticate_Sales_Order">Remote Authanticate</button>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-5 col-md-5">
                        <input id:#button1 type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            
            <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default" id="validate_Sales_Order"/>
            </div>
        </div>
        }
     <input type="hidden" value="Sales_Order" id="type_Order" />
     <script>
         document.getElementById("validate_Sales_Order").disabled = true;
     </script>
        <div>
            @Html.ActionLink("Back to List", "Sales_Order_view", "Supply")
        </div>
    </div>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")

            <script type="text/javascript"
                    src="http://code.jquery.com/jquery-latest.js">
            </script>

            <script type="text/javascript">
                $(document).ready(function () {
                    $('#Button1').click(function () {
                        location.reload();
                    });
                });
            </script>
        }

IdentitySQLDemo/Views/Supply/Sales_Order_view.cshtml
@model IEnumerable<IdentitySQLDemo.Models.Sales_Order>

@{
    ViewBag.Title = "Sales Orders";
    
}

<h2>Sales Orders </h2>

<p>
    @Html.ActionLink("Create New", "Sales_Order_Inset", "Supply")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Invoice_No)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descriptions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quntity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unit_Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Invoice_No)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descriptions)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quntity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Unit_Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Edit", "Sales_Order_Edit","Home" ,new{ id = item.Invoice_No },null) |
           
            @Html.ActionLink("Delete", "sales_Order_Delete", "Home", new { id = item.Invoice_No },null)
        </td>
    </tr>
}

</table>

IdentitySQLDemo/Views/Supply/Sales_Return_Order_Delete.cshtml
@model IdentitySQLDemo.Models.Sales_Return_Order

@{
    ViewBag.Title = "Sales_Return_Order_Delete";
    
}

<h2>Sales_Return_Order_Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sales_Return_Order</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.SalesRe_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalesRe_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Invoice_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Invoice_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descriptions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descriptions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quntity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quntity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit_Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Sales_Return_Order_view", "Supply")
        </div>
    }
</div>