IdentitySQLDemo/Controllers/CustormerController.cs
using IdentitySQLDemo.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using IdentitySQLDemo.DB_layer;

namespace IdentitySQLDemo.Controllers
{
    public class CustormerController : Controller
    {
        
        //
        // GET: /Custormer/
        [Authorize]
        public ActionResult Index(int? page)
        {

            string selectQuery = "SELECT ID,name,address,email,phone_no FROM customer";
            List<customer> customerList = new List<customer>();

            BusinessLayer businessLayer = new BusinessLayer(selectQuery);
            customerList = businessLayer.GetCustomer();

            return View(customerList.ToPagedList(page ?? 1, 6));

        }
        [Authorize]
        public ActionResult intsertCustomer()
        {
            return View();

        }

        [Authorize]
        [HttpPost]
        public ActionResult intsertCustomer(customer cus)
        {
            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con = new SqlConnection(connectionstring);
            string insertQuery = "INSERT INTO customer(ID,name,address,phone_no,email) VALUES (" + cus.ID + ",'" + cus.name + "','" + cus.address + "'," + cus.phone_no + ",'" + cus.email + "')";
            SqlCommand command2 = new SqlCommand(insertQuery, con);
            con.Open();
            command2.ExecuteNonQuery();
            con.Close();

            return RedirectToAction("intsertCustomer");

        }


        [Authorize]
        [HttpGet]
        public ActionResult search(string search, int? page)
        {
            List<customer> customerList = new List<customer>();
            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con = new SqlConnection(connectionstring);

            string searchQuery = "exec sp_search_customers '" + search + "'";
            
            SqlCommand command3 = new SqlCommand(searchQuery, con);
            con.Open();
            var read = command3.ExecuteReader();
            while (read.Read())
            {

                customer customers = new customer();

                customers.ID = Convert.ToInt32(read["ID"]);
                customers.name = read["name"].ToString();
                customers.address = read["address"].ToString();
                customers.phone_no = Convert.ToInt32(read["phone_no"]);
                customers.email = read["email"].ToString();


                customerList.Add(customers);




            }
            con.Close();

            return View(customerList.ToPagedList(page ?? 1, 6));

        }
        [Authorize]
        [HttpGet]
        public ActionResult editCustomer()
        {
            return View();

        }

        [Authorize]
        [HttpPost]
        public ActionResult editCustomer(customer cus, int id)
        {
            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con = new SqlConnection(connectionstring);
            string editQuery = "UPDATE customer SET ID =" + cus.ID + ",name ='" + cus.name + "',address ='" + cus.address + "',phone_no=" + cus.phone_no + ",email='" + cus.email + "'WHERE ID = " + id + "";
            SqlCommand command4 = new SqlCommand(editQuery, con);
            con.Open();
            command4.ExecuteNonQuery();
            con.Close();


            return RedirectToAction("Index");

        }
        [Authorize]
        [HttpGet]
        public ActionResult deleteCustomer()
        {
            return View();

        }

        [Authorize]
        [HttpPost]
        public ActionResult deleteCustomer(customer cus, int id)
        {
            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con = new SqlConnection(connectionstring);
            string deleteQuery = "DELETE FROM customer WHERE ID = " + id + "";
            SqlCommand command5 = new SqlCommand(deleteQuery, con);
            con.Open();
            command5.ExecuteNonQuery();
            con.Close();


            return RedirectToAction("customerList");

        }
        [Authorize]
        public ActionResult Index2(int id)
        {

            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con = new SqlConnection(connectionstring);

            string selectQuery = "SELECT ID,item_name,description,unit_price,quantity FROM Purchase_Order WHERE ID = " + id + "";
            List<Purchase_Order> invoiceList = new List<Purchase_Order>();

            SqlCommand command1 = new SqlCommand(selectQuery, con);
            con.Open();
            var read = command1.ExecuteReader();
            while (read.Read())
            {

                Purchase_Order po = new Purchase_Order();

                po.ID = Convert.ToInt32(read["ID"]);
                po.item_name = read["item_name"].ToString();
                po.description = read["description"].ToString();
                po.unit_price = Convert.ToInt32(read["unit_price"]);
                po.quantity = Convert.ToInt32(read["quantity"]);

                invoiceList.Add(po);




            }
            con.Close();

            return View(invoiceList);

        }

        [Authorize]
        public PartialViewResult Index3(int id)
        {

            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con = new SqlConnection(connectionstring);

            string selectQuery = "SELECT ID,item_name,description,unit_price,quantity FROM Purchase_Order WHERE ID = " + id + "";
            List<Purchase_Order> invoiceList = new List<Purchase_Order>();

            SqlCommand command1 = new SqlCommand(selectQuery, con);
            con.Open();
            var read = command1.ExecuteReader();
            while (read.Read())
            {

                Purchase_Order po = new Purchase_Order();

                po.ID = Convert.ToInt32(read["ID"]);
                po.item_name = read["item_name"].ToString();
                po.description = read["description"].ToString();
                po.unit_price = Convert.ToInt32(read["unit_price"]);
                po.quantity = Convert.ToInt32(read["quantity"]);

                invoiceList.Add(po);




            }
            con.Close();

            return PartialView("_index3", invoiceList);

        }

        [Authorize]
        [HttpGet]
        public ActionResult insertInvoice()
        {

            List<Purchase_Order> po = new List<Purchase_Order> { new Purchase_Order { ID = 0, item_name = "", description = "", unit_price = 0, quantity = 0 } };
            return View(po);

        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult insertInvoice(List<Purchase_Order> po)
        {

            if (ModelState.IsValid)
            {
                string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
                SqlConnection con2 = new SqlConnection(connectionstring);

                con2.Open();
                foreach (var pos in po)
                {
                    string insertQuery = "INSERT INTO Purchase_Order(ID,item_name,description,unit_price,quantity) VALUES (" + pos.ID + ",'" + pos.item_name + "','" + pos.description + "'," + pos.unit_price + "," + pos.quantity + ")";
                    SqlCommand command2 = new SqlCommand(insertQuery, con2);

                    command2.ExecuteNonQuery();

                }
                ViewBag.Message = "Data succesfully saved";
                ModelState.Clear();
                con2.Close();

            }
            return View(po);
        }
        [Authorize]
        [HttpGet]
        public ActionResult editInvoice()
        {
            return View();
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult editInvoice(Purchase_Order po, int id)
        {
            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con3 = new SqlConnection(connectionstring);

            con3.Open();
            string editQuery = "UPDATE Purchase_Order SET ID=" + po.ID + ",item_name='" + po.item_name + "',description='" + po.description + "',unit_price=" + po.unit_price + ",quantity=" + po.quantity + " WHERE ID = " + id + "";
            SqlCommand command3 = new SqlCommand(editQuery, con3);

            command3.ExecuteNonQuery();


            ViewBag.Message = "Data succesfully saved";

            con3.Close();


            return View();
        }
        [Authorize]
        [HttpGet]
        public ActionResult deleteInvoice()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult deleteInvoice(Purchase_Order po, int id)
        {

            string connectionstring = ConfigurationManager.ConnectionStrings["UsersContext"].ConnectionString;
            SqlConnection con3 = new SqlConnection(connectionstring);

            con3.Open();
            string deleteQuery = "DELETE FROM Purchase_Order WHERE ID = " + id + "";
            SqlCommand command3 = new SqlCommand(deleteQuery, con3);

            command3.ExecuteNonQuery();
            con3.Close();
            return View();
        }
    }
}

IdentitySQLDemo/Views/Custormer/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<IdentitySQLDemo.Models.customer>
<div style="float:right;padding-right:200px" >
    @{
        ViewBag.Title = "Index";
    }


    <p style="padding-top:70px"  >

        @using (Html.BeginForm("search", "Customer", FormMethod.Get))
{
   
        <b> Enter customer name:</b>
        @Html.TextBox("search") <input type="submit" value="Search" />
    
}
        <hr />
    </p>
   
    <table class="table">
        <tr><th>
            @Html.DisplayNameFor(model => model.First().ID)</th>
            <th>
                @Html.DisplayNameFor(model => model.First().name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().phone_no)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().email)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr><td>
                   @Html.DisplayFor(modelItem => item.ID)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.phone_no)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.ActionLink("Edit", "editCustomer", "Customer", new { id = item.ID }, null) |
                    @Html.ActionLink("Delete", "deleteCustomer", "Customer", new { id = item.ID },null) |

                    <a href="javascript:;" data-toggle="collapse" data-target="#demo1"><i class="fa fa-fw fa-arrows-v"></i> View <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="demo1" class="collapse nav nav-tabs nav-stacked">
                        <li>
                            @Html.ActionLink("Purchase Order", "Index2", "Custormer",  new { id = item.ID }, null)
                        </li>
                        <li>
                            @Html.ActionLink("Purchase Return Order", "Index2", "Custormer", new { id = item.ID }, null)
                        </li>

                    </ul>



</td>
            </tr>
        }

    </table>

    <center>
        @Html.PagedListPager(Model, page => Url.Action("search", new { page, search = Request.QueryString["search"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
    </center>
</div>

IdentitySQLDemo/Views/Custormer/Index2.cshtml
@model IEnumerable<IdentitySQLDemo.Models.Purchase_Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
<script src="~/signalr/hubs"></script>

<h2>Index</h2>
<div style="float:right;padding-right:200px">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.item_name)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.num)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.unit_price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total_price)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.item_name)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.num)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.unit_price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.total_price)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Total)
                    </td>*@
                <td>
                    @Html.ActionLink("Edit", "editInvoice", "Custormer", new { id = item.ID }, null) |
                    
                    @Html.ActionLink("Delete", "deleteInvoice", "Custormer", new { id = item.ID }, null)
                    <script type="text/javascript">

                        function sendIncoice() {
                                $.connection.hub.start().done(function () {
                                    var chat = $.connection.chatHub;
                                    chat.server.invoiceSender('@User.Identity.Name', '@item.ID', $('#name').val(), $('#invoice_type').val());
                                    });
                               }

                    </script>
                    <button class="md-trigger" type="button" data-modal="modal-19">Open dialog</button>
                </td>
            </tr>

        }

    </table>
    @*<input type="button" id="authorize" value="Athuorize" onclick="sendIncoice()" />*@
    
    <div id="popup_sendNotification" style="display: none;">
        <div class="pull-left">            
            <input type="text" class="text-success" id="name" />
            <div class="md-content">
                <button type="button" id="authorize" onclick="sendIncoice()">Athorize</button>
            </div>
        </div>
    </div>
    
</div>
<input type="hidden" value="PurchaseOrder" id="invoice_type">

IdentitySQLDemo/Views/Custormer/deleteCustomer.cshtml
@model IdentitySQLDemo.Models.customer

@{
    ViewBag.Title = "deleteCustomer";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
   
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="padding-left:400px">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IdentitySQLDemo/Views/Custormer/deleteInvoice.cshtml
@model IdentitySQLDemo.Models.Purchase_Order

@{
    ViewBag.Title = "deleteInvoice";
}

<h2>deleteInvoice</h2>

<h3>Are you sure you want to delete this?</h3>


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }

IdentitySQLDemo/Views/Custormer/editCustomer.cshtml
@model IdentitySQLDemo.Models.customer

@{
    ViewBag.Title = "editCustomer";
}
<div style="float:right;padding-right:200px">
<div style="float:right">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>customer</h4>
            <hr />
            @Html.ValidationSummary(true)
           

            <div class="form-group">
                @Html.LabelFor(model => model.ID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID)
                    @Html.ValidationMessageFor(model => model.ID)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name)
                    @Html.ValidationMessageFor(model => model.name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address)
                    @Html.ValidationMessageFor(model => model.address)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.phone_no, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phone_no)
                    @Html.ValidationMessageFor(model => model.phone_no)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email)
                    @Html.ValidationMessageFor(model => model.email)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
</div>

IdentitySQLDemo/Views/Custormer/editInvoice.cshtml
@model IdentitySQLDemo.Models.Purchase_Order

@{
    ViewBag.Title = "editInvoice";
}

<h2>editInvoice</h2>
<div style="float:right;padding-right:200px">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <table class="table-condensed" id="dataTable">
            <tr>
                <th> <center>  customer ID  </center> </th>
                <th> <center>  Item name  </center>   </th>
                <th> <center> Description  </center>  </th>
                <th>  <center>   Unit Price</center>  </th>
                <th> <center>    Quantity  </center>  </th>

                <th></th>
            </tr>


            <tr>
                @*<td> @Html.TextBoxFor(model => model.ID)</td>
                    <td> @Html.TextBoxFor(model => model.item_name) </td>
                    <td> @Html.TextBoxFor(model => model.description)</td>
                    <td> @Html.TextBoxFor(model => model.unit_price)</td>
                    <td> @Html.TextBoxFor(model => model.quantity)</td>*@
                <td>
                    @Html.EditorFor(model => model.ID)

                </td>
                <td>
                    @Html.EditorFor(model => model.item_name)

                </td>
                <td>
                    @Html.EditorFor(model => model.description)

                </td>
                <td>
                    @Html.EditorFor(model => model.unit_price)

                </td>
                <td>
                    @Html.EditorFor(model => model.quantity)

                </td>
                <td></td>


            </tr>







        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

IdentitySQLDemo/Views/Custormer/insertInvoice.cshtml
@model List<IdentitySQLDemo.Models.Purchase_Order>

@{

}

<h2>intsertInvoice</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Purchase_Order</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div><a href="#" id="addNew">Add New</a></div>


        <table class="table-condensed" id="dataTable">
            <tr>
                <th> <center>  customer ID  </center> </th>
                <th> <center>  Item name  </center>   </th>
                <th> <center> Description  </center>  </th>
                <th>  <center>   Unit Price</center>  </th>
                <th> <center>    Quantity  </center>  </th>

                <th></th>
            </tr>


            <tr>
                @if (Model != null && Model.Count > 0)
                {

                    var j = 0;
                    foreach (var i in Model)
                    {
                        @*<td> @Html.TextBoxFor(model => model.ID)</td>
                            <td> @Html.TextBoxFor(model => model.item_name) </td>
                            <td> @Html.TextBoxFor(model => model.description)</td>
                            <td> @Html.TextBoxFor(model => model.unit_price)</td>
                            <td> @Html.TextBoxFor(model => model.quantity)</td>*@
                        <td>
                            @Html.EditorFor(model => model[j].ID)

                        </td>
                        <td>
                            @Html.EditorFor(model => model[j].item_name)

                        </td>
                        <td>
                            @Html.EditorFor(model => model[j].description)

                        </td>
                        <td>
                            @Html.EditorFor(model => model[j].unit_price)

                        </td>
                        <td>
                            @Html.EditorFor(model => model[j].quantity)

                        </td>
                        <td></td>


                        j++;

                    }

                }

            </tr>
        </table>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button id="sendInvoice" type="button"></button>
                @*<input type="submit" value="Create" class="btn btn-default" />*@
            </div>
        </div>
    </div>
}}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {

            //1. Add new row
            $("#addNew").click(function (e) {
                e.preventDefault();

                var $tableBody = $("#dataTable");

                //if ($("#dataTable tr").length > 5) {
                //    alert('You can only add 5 record at a time for the Demo purpose!');
                //    return false;
                //}


                var $trLast = $tableBody.find("tr:last");
                var $trNew = $trLast.clone();

                var suffix = $trNew.find(':input:first').attr('name').match(/\d+/);
                $trNew.find("td:last").html('<a href="#" class="remove">Remove</a>');
                $.each($trNew.find(':input'), function (i, val) {
                    // Replaced Name
                    var oldN = $(this).attr('name');
                    var newN = oldN.replace('[' + suffix + ']', '[' + (parseInt(suffix) + 1) + ']');
                    $(this).attr('name', newN);
                    //Replaced value
                    var type = $(this).attr('type');
                    if (type.toLowerCase() == "text") {
                        $(this).attr('value', '');
                    }

                    // If you have another Type then replace with default value
                    $(this).removeClass("input-validation-error");

                });
                $trLast.after($trNew);

                // Re-assign Validation
                var form = $("form")
                    .removeData("validator")
                    .removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse(form);
            });

            // 2. Remove
            //$('a.remove').live("click", function (e) {   --> this is for old jquery library
            //$('body').on("click", 'a.remove', function (e) {
            //    e.preventDefault();
            //    $(this).parent().parent().parent().parent().remove();
            //});

        });
    </script>
}

IdentitySQLDemo/Views/Custormer/intsertCustomer.cshtml
@model IdentitySQLDemo.Models.customer

@{

}


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal" style="float:right">
            <h4>intsertCustomer</h4>
            <hr />
            @Html.ValidationSummary(true)
            <div>
                @Html.LabelFor(model => model.ID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID)
                    @Html.ValidationMessageFor(model => model.ID)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name)
                    @Html.ValidationMessageFor(model => model.name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address)
                    @Html.ValidationMessageFor(model => model.address)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.phone_no, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phone_no)
                    @Html.ValidationMessageFor(model => model.phone_no)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email)
                    @Html.ValidationMessageFor(model => model.email)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

   

IdentitySQLDemo/Views/Custormer/search.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<IdentitySQLDemo.Models.customer>

    @{
        ViewBag.Title = "search";
        
    }

    <h2>search</h2>

    <div style="float:right;padding-right:200px">
        <table class="table">
            <tr><th>
                    @Html.DisplayNameFor(model => model.First().ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().phone_no)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().email)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>

                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.phone_no)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "editCustomer", "Customer", new { id = item.ID }, null) |
                        @Html.ActionLink("Delete", "deleteCustomer", "Customer", new { id = item.ID }, null) |

                        <a href="javascript:;" data-toggle="collapse" data-target="#demo1"><i class="fa fa-fw fa-arrows-v"></i> View <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo1" class="collapse nav nav-tabs nav-stacked">
                            <li>
                                @Html.ActionLink("Purchase Order", "Index2", "Custormer", new { id = item.ID }, null)
                            </li>
                            <li>
                                @Html.ActionLink("Purchase Return Order", "Index2", "Custormer", new { id = item.ID }, null)
                            </li>

                        </ul>
                </tr>
            }

        </table>
        <center>
            @Html.PagedListPager(Model, page => Url.Action("search", new { page, search = Request.QueryString["search"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
        </center>
    </div>